pipeline {
    agent any 
    stages {
        stage('Say hello') {
            steps {
                echo 'Hello world!' 
            }
        }
        stage('Build AMI') {
            steps {
                /usr/local/bin/packer build packer/packer.json
            }
        }
    }
}
